import type { DocumentStatus, RequiredDocumentKey, ScrutinyChecklist } from './types';
import { iso } from '../dateUtil';

function allDocs(overrides: Partial<Record<RequiredDocumentKey, DocumentStatus>> = {}): Record<RequiredDocumentKey, DocumentStatus> {
  return {
    commercialInvoice: 'Received',
    packingList: 'Received',
    billOfLadingOrAirwaybill: 'Received',
    certificateOfOrigin: 'Received',
    inspectionCertificate: 'Not Applicable',
    insuranceCertificate: 'Not Applicable',
    beneficiaryCertificate: 'Received',
    gspCertificate: 'Not Applicable',
    ...overrides,
  };
}

// Beneficiary (the exporting legal entity) by operating unit — see letters/shared.ts
// for the same Israq Group entities used in bank correspondence.
const BENEFICIARY_BY_UNIT: Record<string, string> = {
  'Apex Spinning Mills': 'Israq Spinning Mills Limited',
  'Desh Fabrics & Weaving': 'Israq Textile Mills Limited',
  'Green Dyeing & Finishing': 'Israq Cotton Mills Limited',
};

const BENEFICIARY_ADDRESS = 'Israq Group Industrial Complex, Gazipur, Dhaka, Bangladesh';

export const SAMPLE_SCRUTINY_CHECKLISTS: ScrutinyChecklist[] = [
  {
    id: 'scrutiny-1',
    linkedLcId: 'lc-1',
    scrutinyDate: iso(-238),
    scrutinizedBy: 'Md. Anisur Rahman',
    lcNumber: 'ILC-2026-0142',
    lcOpeningDate: iso(-240),
    lcExpiryDate: iso(-210),
    applicantName: 'H&M Hennes & Mauritz GBC AB',
    applicantAddress: 'H&M Hennes & Mauritz GBC AB — Registered Office, Stockholm, Sweden',
    beneficiaryName: BENEFICIARY_BY_UNIT['Apex Spinning Mills'],
    beneficiaryAddress: BENEFICIARY_ADDRESS,
    piNumber: 'PI-AS-3391',
    piDate: iso(-245),
    piQuantity: 45000,
    piValue: 100000,
    currency: 'USD',
    lcQuantity: 45000,
    lcValue: 100000,
    shipmentDate: iso(-236),
    latestShipmentDate: iso(-235),
    paymentDurationDays: 0,
    paymentTerms: 'Sight L/C — payment on presentation of compliant documents',
    partialShipmentAllowed: true,
    partialPaymentClause: '',
    quantityTolerancePct: 5,
    issuingBank: 'Standard Chartered Bank, Stockholm Corporate Branch',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    branch: 'Stockholm Corporate Branch',
    chargingHeads: "All charges outside Bangladesh on Applicant's account",
    reimbursementInstructions: 'Reimbursement by SWIFT authenticated MT202 on first demand',
    hsCode: '5205.11',
    countryOfOrigin: 'Bangladesh',
    destination: 'Stockholm, Sweden',
    incoterms: 'FOB Chattogram',
    documents: allDocs(),
    masterLcOrContract: 'MLC-2025-0089',
    beneficiaryBIN: '004587962-0102',
    specialConditions: 'Nil',
    additionalClauses: 'Nil',
    restrictedClauses: '',
    remarks:
      'Partial payment clause was not clearly defined at the time of scrutiny — flagged for clarification with the buyer\'s bank before shipment. This gap later contributed to the ~$8,000 realization dispute tracked in LC Tracking.',
  },
  {
    id: 'scrutiny-2',
    linkedLcId: 'lc-2',
    scrutinyDate: iso(-98),
    scrutinizedBy: 'Farhana Akter',
    lcNumber: 'ILC-2026-0158',
    lcOpeningDate: iso(-100),
    lcExpiryDate: iso(-20),
    applicantName: 'Metro AG Sourcing',
    applicantAddress: 'Metro AG Sourcing — Registered Office, Frankfurt, Germany',
    beneficiaryName: BENEFICIARY_BY_UNIT['Desh Fabrics & Weaving'],
    beneficiaryAddress: BENEFICIARY_ADDRESS,
    piNumber: 'PI-DF-2207',
    piDate: iso(-104),
    piQuantity: 88000,
    piValue: 220000,
    currency: 'EUR',
    lcQuantity: 88000,
    lcValue: 220000,
    shipmentDate: iso(-55),
    latestShipmentDate: iso(-50),
    paymentDurationDays: 0,
    paymentTerms: 'Sight L/C — payment on presentation of compliant documents',
    partialShipmentAllowed: true,
    partialPaymentClause: 'Partial payments accepted against pro-rata partial shipments',
    quantityTolerancePct: 5,
    issuingBank: 'Commerzbank AG, Frankfurt Trade Finance Branch',
    advisingBank: 'The City Bank Ltd, Gulshan Branch',
    branch: 'Frankfurt Trade Finance Branch',
    chargingHeads: "All charges outside Germany on Applicant's account",
    reimbursementInstructions: 'Reimbursement by SWIFT authenticated MT202 on first demand',
    hsCode: '5208.52',
    countryOfOrigin: 'Bangladesh',
    destination: 'Frankfurt, Germany',
    incoterms: 'CFR Hamburg',
    documents: allDocs({ inspectionCertificate: 'Received' }),
    masterLcOrContract: 'MLC-2025-0104',
    beneficiaryBIN: '004587962-0103',
    specialConditions: 'Nil',
    additionalClauses: 'Nil',
    restrictedClauses: '',
  },
  {
    id: 'scrutiny-3',
    linkedLcId: 'lc-3',
    scrutinyDate: iso(-58),
    scrutinizedBy: 'Shafiul Islam',
    lcNumber: 'ILC-2026-0177',
    lcOpeningDate: iso(-60),
    lcExpiryDate: iso(4),
    applicantName: 'Primark Trading (Ireland) Ltd',
    applicantAddress: 'Primark Trading (Ireland) Ltd — Registered Office, Dublin, Ireland',
    beneficiaryName: BENEFICIARY_BY_UNIT['Green Dyeing & Finishing'],
    beneficiaryAddress: BENEFICIARY_ADDRESS,
    piNumber: 'PI-GD-1875',
    piDate: iso(-63),
    piQuantity: 38000,
    piValue: 95000,
    currency: 'EUR',
    lcQuantity: 38000,
    lcValue: 95000,
    shipmentDate: iso(-20),
    latestShipmentDate: iso(-17),
    paymentDurationDays: 0,
    paymentTerms: 'Sight L/C — payment on presentation of compliant documents',
    partialShipmentAllowed: false,
    partialPaymentClause: 'Not applicable — partial shipment not allowed',
    quantityTolerancePct: 3,
    issuingBank: 'Citibank N.A., Dublin Branch',
    advisingBank: 'Eastern Bank Ltd, Motijheel Branch',
    branch: 'Dublin Branch',
    chargingHeads: "All charges outside Ireland on Applicant's account",
    reimbursementInstructions: 'Reimbursement by SWIFT authenticated MT202 on first demand',
    hsCode: '5209.42',
    countryOfOrigin: 'Bangladesh',
    destination: 'Dublin, Ireland',
    incoterms: 'FOB Chattogram',
    documents: allDocs(),
    masterLcOrContract: 'MLC-2025-0119',
    beneficiaryBIN: '004587962-0104',
    specialConditions: 'Nil',
    additionalClauses: 'Nil',
    restrictedClauses: '',
  },
  {
    id: 'scrutiny-4',
    linkedLcId: 'lc-4',
    scrutinyDate: iso(-78),
    scrutinizedBy: 'Md. Anisur Rahman',
    lcNumber: 'ILC-2026-0163',
    lcOpeningDate: iso(-80),
    lcExpiryDate: iso(35),
    applicantName: 'Walmart Global Sourcing',
    applicantAddress: 'Walmart Global Sourcing — Registered Office, Hong Kong',
    beneficiaryName: BENEFICIARY_BY_UNIT['Apex Spinning Mills'],
    beneficiaryAddress: BENEFICIARY_ADDRESS,
    piNumber: 'PI-AS-3402',
    piDate: iso(-85),
    piQuantity: 80000,
    piValue: 205000,
    currency: 'USD',
    lcQuantity: 80000,
    lcValue: 180000,
    shipmentDate: iso(-5),
    latestShipmentDate: iso(5),
    paymentDurationDays: 0,
    paymentTerms: 'Sight L/C — payment on presentation of compliant documents',
    partialShipmentAllowed: true,
    partialPaymentClause: 'Partial payments accepted against pro-rata partial shipments',
    quantityTolerancePct: 5,
    issuingBank: 'HSBC Bank, Hong Kong Main Office',
    advisingBank: 'HSBC, Dhaka Branch',
    branch: 'Hong Kong Main Office',
    chargingHeads: "All charges outside Hong Kong on Applicant's account",
    reimbursementInstructions: 'Reimbursement by SWIFT authenticated MT202 on first demand',
    hsCode: '5208.52',
    countryOfOrigin: 'Bangladesh',
    destination: 'Long Beach, USA',
    incoterms: 'FOB Chattogram',
    documents: allDocs(),
    masterLcOrContract: 'MLC-2025-0142',
    beneficiaryBIN: '004587962-0102',
    specialConditions: 'Nil',
    additionalClauses: 'Nil',
    restrictedClauses: '',
    remarks: 'LC amount opened short of the PI value — raised with buyer for a possible amendment before shipment.',
  },
  {
    id: 'scrutiny-5',
    linkedLcId: 'lc-6',
    scrutinyDate: iso(-48),
    scrutinizedBy: 'Shafiul Islam',
    lcNumber: 'ILC-2026-0185',
    lcOpeningDate: iso(-50),
    lcExpiryDate: iso(60),
    applicantName: 'Target Sourcing Services',
    applicantAddress: 'Target Sourcing Services — Registered Office, New York, USA',
    beneficiaryName: BENEFICIARY_BY_UNIT['Green Dyeing & Finishing'],
    beneficiaryAddress: BENEFICIARY_ADDRESS,
    piNumber: 'PI-GD-1891',
    piDate: iso(-53),
    piQuantity: 64000,
    piValue: 160000,
    currency: 'USD',
    lcQuantity: 64000,
    lcValue: 160000,
    shipmentDate: iso(45),
    latestShipmentDate: iso(52),
    paymentDurationDays: 0,
    paymentTerms: 'Sight L/C — payment on presentation of compliant documents',
    partialShipmentAllowed: true,
    partialPaymentClause: 'Partial payments accepted against pro-rata partial shipments',
    quantityTolerancePct: 5,
    issuingBank: 'Deutsche Bank AG, New York Branch',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    branch: 'New York Branch',
    chargingHeads: "All charges outside USA on Applicant's account",
    reimbursementInstructions: 'Reimbursement by SWIFT authenticated MT202 on first demand',
    hsCode: '6109.10',
    countryOfOrigin: 'Bangladesh',
    destination: 'Savannah, USA',
    incoterms: 'FOB Chattogram',
    documents: allDocs({ inspectionCertificate: 'Required' }),
    masterLcOrContract: 'MLC-2025-0155',
    beneficiaryBIN: '004587962-0104',
    specialConditions: 'Nil',
    additionalClauses: 'Nil',
    restrictedClauses: '',
    remarks: 'Only a narrow window between latest shipment date and LC expiry — coordinate document presentation closely with the advising bank.',
  },
  {
    id: 'scrutiny-6',
    linkedLcId: 'lc-8',
    scrutinyDate: iso(-128),
    scrutinizedBy: 'Farhana Akter',
    lcNumber: 'ILC-2026-0134',
    lcOpeningDate: iso(-130),
    lcExpiryDate: iso(10),
    applicantName: 'Carrefour Import S.A.S.',
    applicantAddress: 'Carrefour Import S.A.S. — Registered Office, Seoul, South Korea',
    beneficiaryName: BENEFICIARY_BY_UNIT['Desh Fabrics & Weaving'],
    beneficiaryAddress: BENEFICIARY_ADDRESS,
    piNumber: 'PI-DF-2198',
    piDate: iso(-134),
    piQuantity: 35200,
    piValue: 88000,
    currency: 'EUR',
    lcQuantity: 35200,
    lcValue: 88000,
    shipmentDate: iso(-35),
    latestShipmentDate: iso(-30),
    paymentDurationDays: 0,
    paymentTerms: 'Sight L/C — payment on presentation of compliant documents',
    partialShipmentAllowed: true,
    partialPaymentClause: 'Partial payments accepted against pro-rata partial shipments',
    quantityTolerancePct: 5,
    issuingBank: 'Woori Bank, Seoul Head Office',
    advisingBank: 'Brac Bank Ltd, Gulshan Branch',
    branch: 'Seoul Head Office',
    chargingHeads: "All charges outside South Korea on Applicant's account",
    reimbursementInstructions: 'Reimbursement by SWIFT authenticated MT202 on first demand',
    hsCode: '5208.52',
    countryOfOrigin: 'Bangladesh',
    destination: 'Busan, South Korea',
    incoterms: 'CFR Busan',
    documents: allDocs(),
    masterLcOrContract: 'MLC-2025-0076',
    beneficiaryBIN: '',
    specialConditions: 'Nil',
    additionalClauses: 'Nil',
    restrictedClauses: "Documents must be presented through the issuing bank's nominated correspondent only; third-party negotiation not acceptable",
    remarks: 'Restricted negotiation clause and missing BIN on file both require resolution before documents are presented.',
  },
];
