import type { LoanFacility } from './types';
import { iso } from './dateUtil';

export const LOAN_TYPES = ['STL', 'UPAS', 'OD', 'EDF'] as const;

// The four Israq Group units — each one maintains its own STL, UPAS, OD, and
// EDF facilities (see letters/shared.ts GROUP_ENTITIES for the same four
// entities as used in bank correspondence).
export const LOAN_UNITS = [
  'Israq Textile Mills Limited',
  'Israq Spinning Mills Limited',
  'Israq Rotor Spinning Mills Limited',
  'Israq Cotton Mills Limited',
];

export const SAMPLE_LOANS: LoanFacility[] = [
  // Israq Textile Mills Limited
  {
    id: 'loan-1',
    facilityNumber: 'STL-2026-061',
    loanType: 'STL',
    unit: 'Israq Textile Mills Limited',
    bank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'BDT',
    principalAmount: 6000000,
    outstandingAmount: 6000000,
    interestRatePct: 10.2,
    disbursementDate: iso(-45),
    maturityDate: iso(40),
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Raw material procurement financing for the current production cycle.',
  },
  {
    id: 'loan-2',
    facilityNumber: 'UPAS-2026-030',
    loanType: 'UPAS',
    unit: 'Israq Textile Mills Limited',
    bank: 'The City Bank Ltd, Gulshan Branch',
    currency: 'USD',
    principalAmount: 50000,
    outstandingAmount: 50000,
    interestRatePct: 7.6,
    disbursementDate: iso(-95),
    maturityDate: iso(-8),
    linkedLcNumber: 'ILC-2026-0121',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Deferred acceptance financing against the Marks & Spencer import LC; adjustment overdue.',
  },
  {
    id: 'loan-3',
    facilityNumber: 'OD-2026-014',
    loanType: 'OD',
    unit: 'Israq Textile Mills Limited',
    bank: 'Eastern Bank Ltd, Motijheel Branch',
    currency: 'BDT',
    principalAmount: 7500000,
    outstandingAmount: 6900000,
    interestRatePct: 11.8,
    disbursementDate: iso(-320),
    maturityDate: iso(25),
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Revolving working-capital limit; annual renewal review due this quarter.',
  },
  {
    id: 'loan-4',
    facilityNumber: 'EDF-2026-115',
    loanType: 'EDF',
    unit: 'Israq Textile Mills Limited',
    bank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    principalAmount: 70000,
    outstandingAmount: 0,
    interestRatePct: 4.5,
    disbursementDate: iso(-160),
    maturityDate: iso(-20),
    linkedLcNumber: 'ILC-2026-0142',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Bangladesh Bank refinance drawn against the H&M export LC; fully adjusted on realization.',
  },

  // Israq Spinning Mills Limited
  {
    id: 'loan-5',
    facilityNumber: 'STL-2026-062',
    loanType: 'STL',
    unit: 'Israq Spinning Mills Limited',
    bank: 'HSBC, Dhaka Branch',
    currency: 'BDT',
    principalAmount: 4200000,
    outstandingAmount: 1500000,
    interestRatePct: 10.0,
    disbursementDate: iso(-140),
    maturityDate: iso(55),
    responsiblePerson: 'Md. Anisur Rahman',
  },
  {
    id: 'loan-6',
    facilityNumber: 'UPAS-2026-031',
    loanType: 'UPAS',
    unit: 'Israq Spinning Mills Limited',
    bank: 'Prime Bank Ltd, Dhaka',
    currency: 'USD',
    principalAmount: 42000,
    outstandingAmount: 42000,
    interestRatePct: 7.4,
    disbursementDate: iso(-60),
    maturityDate: iso(6),
    linkedLcNumber: 'ILC-2026-0163',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Deferred acceptance financing against the Walmart import LC; nearing adjustment.',
  },
  {
    id: 'loan-7',
    facilityNumber: 'OD-2026-015',
    loanType: 'OD',
    unit: 'Israq Spinning Mills Limited',
    bank: 'Mutual Trust Bank Ltd, Dhaka',
    currency: 'BDT',
    principalAmount: 5000000,
    outstandingAmount: 4300000,
    interestRatePct: 12.2,
    disbursementDate: iso(-260),
    maturityDate: iso(-10),
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Renewal review overdue; bank requesting updated financials before extension.',
  },
  {
    id: 'loan-8',
    facilityNumber: 'EDF-2026-116',
    loanType: 'EDF',
    unit: 'Israq Spinning Mills Limited',
    bank: 'Dutch-Bangla Bank Ltd, Motijheel Branch',
    currency: 'USD',
    principalAmount: 65000,
    outstandingAmount: 65000,
    interestRatePct: 4.5,
    disbursementDate: iso(-25),
    maturityDate: iso(155),
    linkedLcNumber: 'ILC-2026-0185',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Bangladesh Bank refinance drawn against the Target export LC.',
  },

  // Israq Rotor Spinning Mills Limited
  {
    id: 'loan-9',
    facilityNumber: 'STL-2026-063',
    loanType: 'STL',
    unit: 'Israq Rotor Spinning Mills Limited',
    bank: 'Southeast Bank Ltd, Gulshan Branch',
    currency: 'BDT',
    principalAmount: 3500000,
    outstandingAmount: 3500000,
    interestRatePct: 10.5,
    disbursementDate: iso(-20),
    maturityDate: iso(70),
    responsiblePerson: 'Tanvir Ahmed',
  },
  {
    id: 'loan-10',
    facilityNumber: 'UPAS-2026-032',
    loanType: 'UPAS',
    unit: 'Israq Rotor Spinning Mills Limited',
    bank: 'IFIC Bank Ltd, Dhaka',
    currency: 'USD',
    principalAmount: 38000,
    outstandingAmount: 0,
    interestRatePct: 7.8,
    disbursementDate: iso(-130),
    maturityDate: iso(-30),
    linkedLcNumber: 'ILC-2026-0177',
    responsiblePerson: 'Tanvir Ahmed',
    remarks: 'Fully adjusted against the Primark realization.',
  },
  {
    id: 'loan-11',
    facilityNumber: 'OD-2026-016',
    loanType: 'OD',
    unit: 'Israq Rotor Spinning Mills Limited',
    bank: 'Bank Asia Ltd, Gulshan Branch',
    currency: 'BDT',
    principalAmount: 6200000,
    outstandingAmount: 5900000,
    interestRatePct: 11.6,
    disbursementDate: iso(-300),
    maturityDate: iso(3),
    responsiblePerson: 'Tanvir Ahmed',
    remarks: 'Revolving working-capital limit; renewal due within the week.',
  },
  {
    id: 'loan-12',
    facilityNumber: 'EDF-2026-117',
    loanType: 'EDF',
    unit: 'Israq Rotor Spinning Mills Limited',
    bank: 'Trust Bank Ltd, Dhaka',
    currency: 'USD',
    principalAmount: 58000,
    outstandingAmount: 58000,
    interestRatePct: 4.5,
    disbursementDate: iso(-50),
    maturityDate: iso(130),
    linkedLcNumber: 'ILC-2026-0190',
    responsiblePerson: 'Tanvir Ahmed',
    remarks: 'Bangladesh Bank refinance drawn against the LC Waikiki export LC.',
  },

  // Israq Cotton Mills Limited
  {
    id: 'loan-13',
    facilityNumber: 'STL-2026-064',
    loanType: 'STL',
    unit: 'Israq Cotton Mills Limited',
    bank: 'Mercantile Bank Ltd, Dhaka',
    currency: 'BDT',
    principalAmount: 5500000,
    outstandingAmount: 2200000,
    interestRatePct: 10.3,
    disbursementDate: iso(-100),
    maturityDate: iso(65),
    responsiblePerson: 'Farhana Akter',
  },
  {
    id: 'loan-14',
    facilityNumber: 'UPAS-2026-033',
    loanType: 'UPAS',
    unit: 'Israq Cotton Mills Limited',
    bank: 'NCC Bank Ltd, Motijheel Branch',
    currency: 'USD',
    principalAmount: 48000,
    outstandingAmount: 48000,
    interestRatePct: 7.5,
    disbursementDate: iso(-85),
    maturityDate: iso(-3),
    linkedLcNumber: 'ILC-2026-0134',
    responsiblePerson: 'Farhana Akter',
    remarks: 'Deferred acceptance financing against the Carrefour import LC; adjustment overdue.',
  },
  {
    id: 'loan-15',
    facilityNumber: 'OD-2026-017',
    loanType: 'OD',
    unit: 'Israq Cotton Mills Limited',
    bank: 'Pubali Bank Ltd, Dhaka',
    currency: 'BDT',
    principalAmount: 4800000,
    outstandingAmount: 4800000,
    interestRatePct: 12.0,
    disbursementDate: iso(-290),
    maturityDate: iso(45),
    responsiblePerson: 'Farhana Akter',
  },
  {
    id: 'loan-16',
    facilityNumber: 'EDF-2026-118',
    loanType: 'EDF',
    unit: 'Israq Cotton Mills Limited',
    bank: 'One Bank Ltd, Gulshan Branch',
    currency: 'USD',
    principalAmount: 60000,
    outstandingAmount: 22000,
    interestRatePct: 4.5,
    disbursementDate: iso(-175),
    maturityDate: iso(4),
    linkedLcNumber: 'ILC-2026-0158',
    responsiblePerson: 'Farhana Akter',
    remarks: 'Bangladesh Bank refinance against the Metro AG export LC; partially adjusted.',
  },
];
