import type { LoanFacility } from './types';
import { iso } from './dateUtil';

export const LOAN_TYPES = ['STL', 'UPAS', 'OD', 'EDF'] as const;

export const SAMPLE_LOANS: LoanFacility[] = [
  {
    id: 'loan-1',
    facilityNumber: 'STL-2026-041',
    loanType: 'STL',
    unit: 'Apex Spinning Mills',
    bank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'BDT',
    principalAmount: 5000000,
    outstandingAmount: 5000000,
    interestRatePct: 10.5,
    disbursementDate: iso(-60),
    maturityDate: iso(-10),
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Raw cotton procurement financing; adjustment pending buyer realization on ILC-2026-0142.',
  },
  {
    id: 'loan-2',
    facilityNumber: 'STL-2026-052',
    loanType: 'STL',
    unit: 'Desh Fabrics & Weaving',
    bank: 'The City Bank Ltd, Gulshan Branch',
    currency: 'BDT',
    principalAmount: 3000000,
    outstandingAmount: 1200000,
    interestRatePct: 10.0,
    disbursementDate: iso(-150),
    maturityDate: iso(45),
    responsiblePerson: 'Farhana Akter',
  },
  {
    id: 'loan-3',
    facilityNumber: 'UPAS-2026-018',
    loanType: 'UPAS',
    unit: 'Apex Spinning Mills',
    bank: 'HSBC, Dhaka Branch',
    currency: 'USD',
    principalAmount: 45000,
    outstandingAmount: 45000,
    interestRatePct: 7.5,
    disbursementDate: iso(-80),
    maturityDate: iso(5),
    linkedLcNumber: 'ILC-2026-0163',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Deferred acceptance financing against Walmart import of accessories.',
  },
  {
    id: 'loan-4',
    facilityNumber: 'UPAS-2026-022',
    loanType: 'UPAS',
    unit: 'Green Dyeing & Finishing',
    bank: 'Prime Bank Ltd, Dhaka',
    currency: 'USD',
    principalAmount: 60000,
    outstandingAmount: 0,
    interestRatePct: 7.8,
    disbursementDate: iso(-120),
    maturityDate: iso(-20),
    linkedLcNumber: 'ILC-2026-0185',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Fully adjusted on maturity.',
  },
  {
    id: 'loan-5',
    facilityNumber: 'OD-2026-007',
    loanType: 'OD',
    unit: 'Desh Fabrics & Weaving',
    bank: 'Mutual Trust Bank Ltd, Dhaka',
    currency: 'BDT',
    principalAmount: 8000000,
    outstandingAmount: 6500000,
    interestRatePct: 11.5,
    disbursementDate: iso(-300),
    maturityDate: iso(20),
    responsiblePerson: 'Farhana Akter',
    remarks: 'Revolving working-capital limit; due for annual renewal review.',
  },
  {
    id: 'loan-6',
    facilityNumber: 'OD-2026-011',
    loanType: 'OD',
    unit: 'Green Dyeing & Finishing',
    bank: 'Eastern Bank Ltd, Motijheel Branch',
    currency: 'BDT',
    principalAmount: 4000000,
    outstandingAmount: 3800000,
    interestRatePct: 12.0,
    disbursementDate: iso(-200),
    maturityDate: iso(-15),
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Renewal review overdue; bank requesting updated financials before extension.',
  },
  {
    id: 'loan-7',
    facilityNumber: 'EDF-2026-104',
    loanType: 'EDF',
    unit: 'Apex Spinning Mills',
    bank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    principalAmount: 80000,
    outstandingAmount: 80000,
    interestRatePct: 4.5,
    disbursementDate: iso(-40),
    maturityDate: iso(140),
    linkedLcNumber: 'ILC-2026-0142',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Bangladesh Bank refinance drawn against the H&M export LC.',
  },
  {
    id: 'loan-8',
    facilityNumber: 'EDF-2026-109',
    loanType: 'EDF',
    unit: 'Desh Fabrics & Weaving',
    bank: 'Brac Bank Ltd, Gulshan Branch',
    currency: 'USD',
    principalAmount: 55000,
    outstandingAmount: 20000,
    interestRatePct: 4.5,
    disbursementDate: iso(-170),
    maturityDate: iso(6),
    linkedLcNumber: 'ILC-2026-0171',
    responsiblePerson: 'Farhana Akter',
    remarks: 'Partially adjusted from the first Zara realization tranche.',
  },
];
