import type { LC } from './types';
import { iso } from './dateUtil';

export const UNITS = ['Apex Spinning Mills', 'Desh Fabrics & Weaving', 'Green Dyeing & Finishing'];

export const SAMPLE_LCS: LC[] = [
  {
    id: 'lc-1',
    lcNumber: 'ILC-2026-0142',
    beneficiary: 'H&M Hennes & Mauritz GBC AB',
    issuingBank: 'Standard Chartered Bank',
    branch: 'Stockholm Corporate Branch',
    location: 'Stockholm, Sweden',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 100000,
    billType: 'LDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-238),
    issueDate: iso(-240),
    acceptanceDate: iso(-235),
    maturityDate: iso(-210),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Nusrat Jahan',
    media: 'SWIFT TT',
    remarks:
      "Buyer's bank withheld $8,000 citing a missed partial-shipment clause under Art. 45(b); under dispute with legal since realization.",
    advBankReminderDate: iso(-5),
    issuingBankVisitingDate: iso(-30),
    nextVisitingDate: iso(7),
    realizations: [
      {
        id: 'lc-1-r1',
        date: iso(-195),
        currency: 'USD',
        amountFC: 92000,
        exchangeRate: 118.4,
        fddPayOrderDate: iso(-193),
        scbErqBuildUpFC: 13800,
        shortOverValueFC: -300,
        shortOverValueBDT: -35520,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 65357,
        adjustmentDate: iso(-180),
      },
    ],
    // Note: the remaining $8,000 was withheld by the buyer's bank citing a
    // missed partial-shipment clause and has sat unresolved ever since —
    // this is the real incident the tracker proposal was built around.
  },
  {
    id: 'lc-2',
    lcNumber: 'ILC-2026-0158',
    beneficiary: 'Metro AG Sourcing',
    issuingBank: 'Commerzbank AG',
    branch: 'Frankfurt Trade Finance Branch',
    location: 'Frankfurt, Germany',
    advisingBank: 'The City Bank Ltd, Gulshan Branch',
    currency: 'EUR',
    lcValue: 220000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-98),
    issueDate: iso(-100),
    acceptanceDate: iso(-95),
    maturityDate: iso(-20),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: 'No realization received past maturity; advising bank following up with issuing bank on payment status.',
    advBankReminderDate: iso(-3),
    nextVisitingDate: iso(10),
    realizations: [],
  },
  {
    id: 'lc-3',
    lcNumber: 'ILC-2026-0177',
    beneficiary: 'Primark Trading (Ireland) Ltd',
    issuingBank: 'Citibank N.A.',
    branch: 'Dublin Branch',
    location: 'Dublin, Ireland',
    advisingBank: 'Eastern Bank Ltd, Motijheel Branch',
    currency: 'EUR',
    lcValue: 95000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-58),
    issueDate: iso(-60),
    maturityDate: iso(4),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Nusrat Jahan',
    media: 'FDD',
    remarks: 'On track; documents already negotiated, balance expected via advising bank before maturity.',
    advBankReminderDate: iso(-2),
    realizations: [
      {
        id: 'lc-3-r1',
        date: iso(-10),
        currency: 'EUR',
        amountFC: 28500,
        exchangeRate: 128.5,
        fddPayOrderDate: iso(-9),
        scbErqBuildUpFC: 4275,
        shortOverValueFC: -45,
        shortOverValueBDT: -5782.5,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 21973.5,
      },
    ],
  },
  {
    id: 'lc-4',
    lcNumber: 'ILC-2026-0163',
    beneficiary: 'Walmart Global Sourcing',
    issuingBank: 'HSBC Bank',
    branch: 'Hong Kong Main Office',
    location: 'Hong Kong, China',
    advisingBank: 'HSBC, Dhaka Branch',
    currency: 'USD',
    lcValue: 180000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-77),
    issueDate: iso(-80),
    acceptanceDate: iso(-75),
    maturityDate: iso(35),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Nusrat Jahan',
    media: 'SWIFT TT',
    remarks: "Balance expected in further tranches per buyer's payment schedule.",
    realizations: [
      {
        id: 'lc-4-r1',
        date: iso(-40),
        currency: 'USD',
        amountFC: 45000,
        exchangeRate: 117.8,
        fddPayOrderDate: iso(-38),
        scbErqBuildUpFC: 6750,
        shortOverValueFC: -60,
        shortOverValueBDT: -7068,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 31806,
        adjustmentDate: iso(-25),
      },
      {
        id: 'lc-4-r2',
        date: iso(-12),
        currency: 'USD',
        amountFC: 54000,
        exchangeRate: 118.6,
        fddPayOrderDate: iso(-10),
        scbErqBuildUpFC: 8100,
        shortOverValueFC: 20,
        shortOverValueBDT: 2372,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 38426.4,
      },
    ],
  },
  {
    id: 'lc-5',
    lcNumber: 'ILC-2026-0171',
    beneficiary: 'Industria de Diseno Textil, S.A. (Zara)',
    issuingBank: 'BNP Paribas',
    branch: 'Madrid Trade Branch',
    location: 'Madrid, Spain',
    advisingBank: 'Mutual Trust Bank Ltd, Dhaka',
    currency: 'EUR',
    lcValue: 130000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-68),
    issueDate: iso(-70),
    maturityDate: iso(50),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Tanvir Ahmed',
    media: 'Pay Order',
    remarks: "Final tranche pending buyer's quality acceptance sign-off.",
    realizations: [
      {
        id: 'lc-5-r1',
        date: iso(-35),
        currency: 'EUR',
        amountFC: 60000,
        exchangeRate: 127.9,
        fddPayOrderDate: iso(-33),
        scbErqBuildUpFC: 9000,
        shortOverValueFC: -80,
        shortOverValueBDT: -10232,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 38370,
        adjustmentDate: iso(-20),
      },
      {
        id: 'lc-5-r2',
        date: iso(-8),
        currency: 'EUR',
        amountFC: 28400,
        exchangeRate: 128.75,
        fddPayOrderDate: iso(-6),
        scbErqBuildUpFC: 4260,
        shortOverValueFC: -15,
        shortOverValueBDT: -1931.25,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 18282.5,
      },
    ],
  },
  {
    id: 'lc-6',
    lcNumber: 'ILC-2026-0185',
    beneficiary: 'Target Sourcing Services',
    issuingBank: 'Deutsche Bank AG',
    branch: 'New York Branch',
    location: 'New York, USA',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 160000,
    billType: 'IDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-48),
    issueDate: iso(-50),
    acceptanceDate: iso(-45),
    maturityDate: iso(60),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Tanvir Ahmed',
    media: 'SWIFT TT',
    remarks: 'Awaiting second tranche; buyer confirmed remittance instruction on file.',
    realizations: [
      {
        id: 'lc-6-r1',
        date: iso(-20),
        currency: 'USD',
        amountFC: 67200,
        exchangeRate: 118.9,
        fddPayOrderDate: iso(-18),
        scbErqBuildUpFC: 10080,
        shortOverValueFC: -100,
        shortOverValueBDT: -11890,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 79900.8,
        adjustmentDate: iso(-5),
      },
    ],
  },
  {
    id: 'lc-7',
    lcNumber: 'ILC-2026-0121',
    beneficiary: 'Marks & Spencer plc',
    issuingBank: 'Standard Chartered Bank',
    branch: 'London City Branch',
    location: 'London, UK',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 140000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-147),
    issueDate: iso(-150),
    maturityDate: iso(-70),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Nusrat Jahan',
    media: 'SWIFT TT',
    remarks: 'Fully settled, no outstanding issues.',
    realizations: [
      {
        id: 'lc-7-r1',
        date: iso(-100),
        currency: 'USD',
        amountFC: 70000,
        exchangeRate: 117.5,
        fddPayOrderDate: iso(-98),
        scbErqBuildUpFC: 10500,
        shortOverValueFC: 0,
        shortOverValueBDT: 0,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 49350,
      },
      {
        id: 'lc-7-r2',
        date: iso(-75),
        currency: 'USD',
        amountFC: 70000,
        exchangeRate: 118.1,
        fddPayOrderDate: iso(-73),
        scbErqBuildUpFC: 10500,
        shortOverValueFC: 0,
        shortOverValueBDT: 0,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 49602,
      },
    ],
  },
  {
    id: 'lc-8',
    lcNumber: 'ILC-2026-0134',
    beneficiary: 'Carrefour Import S.A.S.',
    issuingBank: 'Woori Bank',
    branch: 'Seoul Head Office',
    location: 'Seoul, South Korea',
    advisingBank: 'Brac Bank Ltd, Gulshan Branch',
    currency: 'EUR',
    lcValue: 88000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-127),
    issueDate: iso(-130),
    maturityDate: iso(10),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Tanvir Ahmed',
    media: 'FDD',
    remarks: 'Fully settled ahead of maturity via sight payment.',
    realizations: [
      {
        id: 'lc-8-r1',
        date: iso(-30),
        currency: 'EUR',
        amountFC: 88000,
        exchangeRate: 126.4,
        fddPayOrderDate: iso(-28),
        scbErqBuildUpFC: 13200,
        shortOverValueFC: -50,
        shortOverValueBDT: -6320,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 66739.2,
        adjustmentDate: iso(-15),
      },
    ],
  },
  {
    id: 'lc-9',
    lcNumber: 'ILC-2026-0190',
    beneficiary: 'LC Waikiki Magazacilik',
    issuingBank: 'ICBC',
    branch: 'Istanbul Branch',
    location: 'Istanbul, Turkey',
    advisingBank: 'Prime Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 175000,
    billType: 'IDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-27),
    issueDate: iso(-30),
    maturityDate: iso(90),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Documents lodged; realization expected on/around maturity.',
    realizations: [],
  },
];
