import type { LC } from './types';
import { iso } from './dateUtil';

export const UNITS = ['Israq Spinning Mills LTD', 'Israq Cotton Mills LTD', 'Israq Textiles mills LTD'];

export const SAMPLE_LCS: LC[] = [
  {
    id: 'lc-1',
    lcNumber: 'ILC-2026-0142',
    beneficiary: 'H&M Hennes & Mauritz GBC AB',
    issuingBank: 'Standard Chartered Bank',
    branch: 'Stockholm Corporate Branch',
    location: 'Stockholm, Sweden',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 100000,
    billType: 'LDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-238),
    issueDate: iso(-240),
    acceptanceDate: iso(-235),
    maturityDate: iso(-210),
    unit: 'Israq Spinning Mills LTD',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Nusrat Jahan',
    media: 'SWIFT TT',
    remarks:
      "Buyer's bank withheld $8,000 citing a missed partial-shipment clause under Art. 45(b); under dispute with legal since realization.",
    advBankReminderDate: iso(-5),
    issuingBankVisitingDate: iso(-30),
    nextVisitingDate: iso(7),
    realizations: [
      {
        id: 'lc-1-r1',
        date: iso(-195),
        currency: 'USD',
        amountFC: 92000,
        exchangeRate: 118.4,
        fddPayOrderDate: iso(-193),
        scbErqBuildUpFC: 13800,
        shortOverValueFC: -300,
        shortOverValueBDT: -35520,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 65357,
        adjustmentDate: iso(-180),
      },
    ],
    // Note: the remaining $8,000 was withheld by the buyer's bank citing a
    // missed partial-shipment clause and has sat unresolved ever since —
    // this is the real incident the tracker proposal was built around.
  },
  {
    id: 'lc-2',
    lcNumber: 'ILC-2026-0158',
    beneficiary: 'Metro AG Sourcing',
    issuingBank: 'Commerzbank AG',
    branch: 'Frankfurt Trade Finance Branch',
    location: 'Frankfurt, Germany',
    advisingBank: 'The City Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 220000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-98),
    issueDate: iso(-100),
    acceptanceDate: iso(-95),
    maturityDate: iso(-20),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: 'No realization received past maturity; advising bank following up with issuing bank on payment status.',
    advBankReminderDate: iso(-3),
    nextVisitingDate: iso(10),
    realizations: [],
  },
  {
    id: 'lc-3',
    lcNumber: 'ILC-2026-0177',
    beneficiary: 'Primark Trading (Ireland) Ltd',
    issuingBank: 'Citibank N.A.',
    branch: 'Dublin Branch',
    location: 'Dublin, Ireland',
    advisingBank: 'Eastern Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 95000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-58),
    issueDate: iso(-60),
    maturityDate: iso(4),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Nusrat Jahan',
    media: 'FDD',
    remarks: 'On track; documents already negotiated, balance expected via advising bank before maturity.',
    advBankReminderDate: iso(-2),
    realizations: [
      {
        id: 'lc-3-r1',
        date: iso(-10),
        currency: 'USD',
        amountFC: 28500,
        exchangeRate: 128.5,
        fddPayOrderDate: iso(-9),
        scbErqBuildUpFC: 4275,
        shortOverValueFC: -45,
        shortOverValueBDT: -5782.5,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 21973.5,
      },
    ],
  },
  {
    id: 'lc-4',
    lcNumber: 'ILC-2026-0163',
    beneficiary: 'Walmart Global Sourcing',
    issuingBank: 'HSBC Bank',
    branch: 'Hong Kong Main Office',
    location: 'Hong Kong, China',
    advisingBank: 'HSBC, Dhaka Branch',
    currency: 'USD',
    lcValue: 180000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-77),
    issueDate: iso(-80),
    acceptanceDate: iso(-75),
    maturityDate: iso(35),
    unit: 'Israq Spinning Mills LTD',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Nusrat Jahan',
    media: 'SWIFT TT',
    remarks: "Balance expected in further tranches per buyer's payment schedule.",
    realizations: [
      {
        id: 'lc-4-r1',
        date: iso(-40),
        currency: 'USD',
        amountFC: 45000,
        exchangeRate: 117.8,
        fddPayOrderDate: iso(-38),
        scbErqBuildUpFC: 6750,
        shortOverValueFC: -60,
        shortOverValueBDT: -7068,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 31806,
        adjustmentDate: iso(-25),
      },
      {
        id: 'lc-4-r2',
        date: iso(-12),
        currency: 'USD',
        amountFC: 54000,
        exchangeRate: 118.6,
        fddPayOrderDate: iso(-10),
        scbErqBuildUpFC: 8100,
        shortOverValueFC: 20,
        shortOverValueBDT: 2372,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 38426.4,
      },
    ],
  },
  {
    id: 'lc-5',
    lcNumber: 'ILC-2026-0171',
    beneficiary: 'Industria de Diseno Textil, S.A. (Zara)',
    issuingBank: 'BNP Paribas',
    branch: 'Madrid Trade Branch',
    location: 'Madrid, Spain',
    advisingBank: 'Mutual Trust Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 130000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-68),
    issueDate: iso(-70),
    maturityDate: iso(50),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Tanvir Ahmed',
    media: 'Pay Order',
    remarks: "Final tranche pending buyer's quality acceptance sign-off.",
    realizations: [
      {
        id: 'lc-5-r1',
        date: iso(-35),
        currency: 'USD',
        amountFC: 60000,
        exchangeRate: 127.9,
        fddPayOrderDate: iso(-33),
        scbErqBuildUpFC: 9000,
        shortOverValueFC: -80,
        shortOverValueBDT: -10232,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 38370,
        adjustmentDate: iso(-20),
      },
      {
        id: 'lc-5-r2',
        date: iso(-8),
        currency: 'USD',
        amountFC: 28400,
        exchangeRate: 128.75,
        fddPayOrderDate: iso(-6),
        scbErqBuildUpFC: 4260,
        shortOverValueFC: -15,
        shortOverValueBDT: -1931.25,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 18282.5,
      },
    ],
  },
  {
    id: 'lc-6',
    lcNumber: 'ILC-2026-0185',
    beneficiary: 'Target Sourcing Services',
    issuingBank: 'Deutsche Bank AG',
    branch: 'New York Branch',
    location: 'New York, USA',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 160000,
    billType: 'IDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-48),
    issueDate: iso(-50),
    acceptanceDate: iso(-45),
    maturityDate: iso(60),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Tanvir Ahmed',
    media: 'SWIFT TT',
    remarks: 'Awaiting second tranche; buyer confirmed remittance instruction on file.',
    realizations: [
      {
        id: 'lc-6-r1',
        date: iso(-20),
        currency: 'USD',
        amountFC: 67200,
        exchangeRate: 118.9,
        fddPayOrderDate: iso(-18),
        scbErqBuildUpFC: 10080,
        shortOverValueFC: -100,
        shortOverValueBDT: -11890,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 79900.8,
        adjustmentDate: iso(-5),
      },
    ],
  },
  {
    id: 'lc-7',
    lcNumber: 'ILC-2026-0121',
    beneficiary: 'Marks & Spencer plc',
    issuingBank: 'Standard Chartered Bank',
    branch: 'London City Branch',
    location: 'London, UK',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 140000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-147),
    issueDate: iso(-150),
    maturityDate: iso(-70),
    unit: 'Israq Spinning Mills LTD',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Nusrat Jahan',
    media: 'SWIFT TT',
    remarks: 'Fully settled, no outstanding issues.',
    realizations: [
      {
        id: 'lc-7-r1',
        date: iso(-100),
        currency: 'USD',
        amountFC: 70000,
        exchangeRate: 117.5,
        fddPayOrderDate: iso(-98),
        scbErqBuildUpFC: 10500,
        shortOverValueFC: 0,
        shortOverValueBDT: 0,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 49350,
      },
      {
        id: 'lc-7-r2',
        date: iso(-75),
        currency: 'USD',
        amountFC: 70000,
        exchangeRate: 118.1,
        fddPayOrderDate: iso(-73),
        scbErqBuildUpFC: 10500,
        shortOverValueFC: 0,
        shortOverValueBDT: 0,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 49602,
      },
    ],
  },
  {
    id: 'lc-8',
    lcNumber: 'ILC-2026-0134',
    beneficiary: 'Carrefour Import S.A.S.',
    issuingBank: 'Woori Bank',
    branch: 'Seoul Head Office',
    location: 'Seoul, South Korea',
    advisingBank: 'Brac Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 88000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-127),
    issueDate: iso(-130),
    maturityDate: iso(10),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Tanvir Ahmed',
    media: 'FDD',
    remarks: 'Fully settled ahead of maturity via sight payment.',
    realizations: [
      {
        id: 'lc-8-r1',
        date: iso(-30),
        currency: 'USD',
        amountFC: 88000,
        exchangeRate: 126.4,
        fddPayOrderDate: iso(-28),
        scbErqBuildUpFC: 13200,
        shortOverValueFC: -50,
        shortOverValueBDT: -6320,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 66739.2,
        adjustmentDate: iso(-15),
      },
    ],
  },
  {
    id: 'lc-9',
    lcNumber: 'ILC-2026-0190',
    beneficiary: 'LC Waikiki Magazacilik',
    issuingBank: 'ICBC',
    branch: 'Istanbul Branch',
    location: 'Istanbul, Turkey',
    advisingBank: 'Prime Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 175000,
    billType: 'IDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-27),
    issueDate: iso(-30),
    maturityDate: iso(90),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Documents lodged; realization expected on/around maturity.',
    realizations: [],
  },
  {
    id: 'lc-10',
    lcNumber: 'ILC-2026-0201',
    beneficiary: 'Tesco Stores Ltd',
    issuingBank: 'TD Bank Group',
    branch: 'Toronto Financial District',
    location: 'Toronto, Canada',
    advisingBank: 'NCC Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 161000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-234),
    issueDate: iso(-236),
    maturityDate: iso(-175),
    unit: 'Israq Spinning Mills LTD',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Tanvir Ahmed',
    media: 'SWIFT TT',
    remarks: 'Fully settled, no outstanding issues.',
    realizations: [
      {
        id: 'lc-10-r1',
        date: iso(-178),
        currency: 'USD',
        amountFC: 161000,
        exchangeRate: 129.05,
        fddPayOrderDate: iso(-176),
        scbErqBuildUpFC: 24150,
        shortOverValueFC: -84.13,
        shortOverValueBDT: -10856.98,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 103885.25,
        adjustmentDate: iso(-163),
      },
    ],
  },
  {
    id: 'lc-11',
    lcNumber: 'ILC-2026-0202',
    beneficiary: 'Next Sourcing Ltd',
    issuingBank: 'Bank of Montreal',
    branch: 'Montreal Branch',
    location: 'Montreal, Canada',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 232000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-156),
    issueDate: iso(-158),
    maturityDate: iso(-78),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Sadia Islam',
    media: 'FDD',
    remarks: 'Fully settled ahead of maturity via sight payment.',
    realizations: [
      {
        id: 'lc-11-r1',
        date: iso(-120),
        currency: 'USD',
        amountFC: 116886,
        exchangeRate: 116.73,
        fddPayOrderDate: iso(-118),
        scbErqBuildUpFC: 17532.9,
        shortOverValueFC: 36.12,
        shortOverValueBDT: 4216.29,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 81864.62,
      },
      {
        id: 'lc-11-r2',
        date: iso(-84),
        currency: 'USD',
        amountFC: 115114,
        exchangeRate: 116.73,
        fddPayOrderDate: iso(-82),
        scbErqBuildUpFC: 17267.1,
        shortOverValueFC: -89.83,
        shortOverValueBDT: -10485.86,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 80623.54,
      },
    ],
  },
  {
    id: 'lc-12',
    lcNumber: 'ILC-2026-0203',
    beneficiary: 'Fast Retailing (Uniqlo) Co.',
    issuingBank: 'UniCredit Bank AG',
    branch: 'Munich Trade Branch',
    location: 'Munich, Germany',
    advisingBank: 'Trust Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 188000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-151),
    issueDate: iso(-153),
    acceptanceDate: iso(-148),
    maturityDate: iso(-70),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Tanvir Ahmed',
    media: 'Pay Order',
    remarks: 'Fully settled; all tranches reconciled with advising bank.',
    realizations: [
      {
        id: 'lc-12-r1',
        date: iso(-73),
        currency: 'USD',
        amountFC: 188000,
        exchangeRate: 116.62,
        fddPayOrderDate: iso(-71),
        scbErqBuildUpFC: 28200,
        shortOverValueFC: 68.93,
        shortOverValueBDT: 8038.62,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 131547.36,
        adjustmentDate: iso(-60),
      },
    ],
  },
  {
    id: 'lc-13',
    lcNumber: 'ILC-2026-0204',
    beneficiary: 'C&A Buying GmbH',
    issuingBank: 'Westpac Banking Corp.',
    branch: 'Sydney CBD Branch',
    location: 'Sydney, Australia',
    advisingBank: 'Midland Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 140000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-257),
    issueDate: iso(-259),
    maturityDate: iso(-192),
    unit: 'Israq Spinning Mills LTD',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Sadia Islam',
    media: 'Pay Order',
    remarks: 'Fully settled, no outstanding issues.',
    realizations: [
      {
        id: 'lc-13-r1',
        date: iso(-194),
        currency: 'USD',
        amountFC: 140000,
        exchangeRate: 128.1,
        fddPayOrderDate: iso(-192),
        scbErqBuildUpFC: 21000,
        shortOverValueFC: -37.03,
        shortOverValueBDT: -4743.54,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 179340,
        adjustmentDate: iso(-184),
      },
    ],
  },
  {
    id: 'lc-14',
    lcNumber: 'ILC-2026-0205',
    beneficiary: 'Kmart Australia Sourcing',
    issuingBank: 'KEB Hana Bank',
    branch: 'Seoul Trade Branch',
    location: 'Seoul, South Korea',
    advisingBank: 'NCC Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 211000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-136),
    issueDate: iso(-138),
    acceptanceDate: iso(-133),
    maturityDate: iso(-71),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Nusrat Jahan',
    media: 'FDD',
    remarks: 'Fully settled; all tranches reconciled with advising bank.',
    realizations: [
      {
        id: 'lc-14-r1',
        date: iso(-80),
        currency: 'USD',
        amountFC: 211000,
        exchangeRate: 117.63,
        fddPayOrderDate: iso(-78),
        scbErqBuildUpFC: 31650,
        shortOverValueFC: -54.16,
        shortOverValueBDT: -6370.84,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 124099.65,
        adjustmentDate: iso(-69),
      },
    ],
  },
  {
    id: 'lc-15',
    lcNumber: 'ILC-2026-0206',
    beneficiary: 'Aldi Sourcing GmbH',
    issuingBank: 'Banco Santander S.A.',
    branch: 'Madrid Central Branch',
    location: 'Madrid, Spain',
    advisingBank: 'Prime Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 69000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-93),
    issueDate: iso(-95),
    maturityDate: iso(-24),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Tanvir Ahmed',
    media: 'FDD',
    remarks: 'Fully settled; all tranches reconciled with advising bank.',
    realizations: [
      {
        id: 'lc-15-r1',
        date: iso(-26),
        currency: 'USD',
        amountFC: 69000,
        exchangeRate: 130.11,
        fddPayOrderDate: iso(-24),
        scbErqBuildUpFC: 10350,
        shortOverValueFC: 64.84,
        shortOverValueBDT: 8436.33,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 53865.54,
        adjustmentDate: iso(-11),
      },
    ],
  },
  {
    id: 'lc-16',
    lcNumber: 'ILC-2026-0207',
    beneficiary: 'Lidl Stiftung & Co. KG',
    issuingBank: 'UniCredit Bank AG',
    branch: 'Munich Trade Branch',
    location: 'Munich, Germany',
    advisingBank: 'Pubali Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 192000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-162),
    issueDate: iso(-164),
    acceptanceDate: iso(-159),
    maturityDate: iso(-89),
    unit: 'Israq Cotton Mills LTD',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Sadia Islam',
    media: 'Pay Order',
    remarks: 'Fully settled; all tranches reconciled with advising bank.',
    realizations: [
      {
        id: 'lc-16-r1',
        date: iso(-122),
        currency: 'USD',
        amountFC: 100723,
        exchangeRate: 127.55,
        fddPayOrderDate: iso(-120),
        scbErqBuildUpFC: 15108.45,
        shortOverValueFC: -52.43,
        shortOverValueBDT: -6687.45,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 128472.19,
      },
      {
        id: 'lc-16-r2',
        date: iso(-96),
        currency: 'USD',
        amountFC: 91277,
        exchangeRate: 127.55,
        fddPayOrderDate: iso(-94),
        scbErqBuildUpFC: 13691.55,
        shortOverValueFC: 70.1,
        shortOverValueBDT: 8941.25,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 116423.81,
      },
    ],
  },
  {
    id: 'lc-17',
    lcNumber: 'ILC-2026-0208',
    beneficiary: 'Decathlon Sourcing',
    issuingBank: 'China Construction Bank',
    branch: 'Beijing Branch',
    location: 'Beijing, China',
    advisingBank: 'IFIC Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 143000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-120),
    issueDate: iso(-122),
    acceptanceDate: iso(-117),
    maturityDate: iso(-57),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Tanvir Ahmed',
    media: 'Pay Order',
    remarks: 'Fully settled; all tranches reconciled with advising bank.',
    realizations: [
      {
        id: 'lc-17-r1',
        date: iso(-97),
        currency: 'USD',
        amountFC: 64870,
        exchangeRate: 129.47,
        fddPayOrderDate: iso(-95),
        scbErqBuildUpFC: 9730.5,
        shortOverValueFC: 71.73,
        shortOverValueBDT: 9286.88,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 83987.19,
      },
      {
        id: 'lc-17-r2',
        date: iso(-66),
        currency: 'USD',
        amountFC: 78130,
        exchangeRate: 129.47,
        fddPayOrderDate: iso(-64),
        scbErqBuildUpFC: 11719.5,
        shortOverValueFC: 58.95,
        shortOverValueBDT: 7632.26,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 101154.91,
      },
    ],
  },
  {
    id: 'lc-18',
    lcNumber: 'ILC-2026-0209',
    beneficiary: 'Gap Inc. Sourcing',
    issuingBank: 'Rabobank International',
    branch: 'Utrecht Branch',
    location: 'Utrecht, Netherlands',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 82000,
    billType: 'LDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-224),
    issueDate: iso(-226),
    maturityDate: iso(-148),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Sadia Islam',
    media: 'Pay Order',
    remarks: 'Fully settled; all tranches reconciled with advising bank.',
    realizations: [
      {
        id: 'lc-18-r1',
        date: iso(-180),
        currency: 'USD',
        amountFC: 39989,
        exchangeRate: 119.35,
        fddPayOrderDate: iso(-178),
        scbErqBuildUpFC: 5998.35,
        shortOverValueFC: 14.26,
        shortOverValueBDT: 1701.93,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 47726.87,
      },
      {
        id: 'lc-18-r2',
        date: iso(-155),
        currency: 'USD',
        amountFC: 42011,
        exchangeRate: 119.35,
        fddPayOrderDate: iso(-153),
        scbErqBuildUpFC: 6301.65,
        shortOverValueFC: -89.86,
        shortOverValueBDT: -10724.79,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 50140.13,
      },
    ],
  },
  {
    id: 'lc-19',
    lcNumber: 'ILC-2026-0210',
    beneficiary: 'Levi Strauss & Co.',
    issuingBank: 'Westpac Banking Corp.',
    branch: 'Sydney CBD Branch',
    location: 'Sydney, Australia',
    advisingBank: 'Prime Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 107000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-113),
    issueDate: iso(-115),
    acceptanceDate: iso(-110),
    maturityDate: iso(-55),
    unit: 'Israq Textiles mills LTD',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Tanvir Ahmed',
    media: 'SWIFT TT',
    remarks: 'Fully settled, no outstanding issues.',
    realizations: [
      {
        id: 'lc-19-r1',
        date: iso(-64),
        currency: 'USD',
        amountFC: 107000,
        exchangeRate: 120.68,
        fddPayOrderDate: iso(-62),
        scbErqBuildUpFC: 16050,
        shortOverValueFC: -20.3,
        shortOverValueBDT: -2449.8,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 77476.56,
        adjustmentDate: iso(-52),
      },
    ],
  },
  {
    id: 'lc-20',
    lcNumber: 'ILC-2026-0211',
    beneficiary: 'PVH Corp (Tommy Hilfiger)',
    issuingBank: 'Barclays Bank plc',
    branch: 'Canary Wharf Branch',
    location: 'London, UK',
    advisingBank: 'HSBC, Dhaka Branch',
    currency: 'USD',
    lcValue: 74000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-134),
    issueDate: iso(-136),
    maturityDate: iso(-60),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Nusrat Jahan',
    media: 'SWIFT TT',
    remarks: 'Fully settled, no outstanding issues.',
    realizations: [
      {
        id: 'lc-20-r1',
        date: iso(-68),
        currency: 'USD',
        amountFC: 74000,
        exchangeRate: 120.02,
        fddPayOrderDate: iso(-66),
        scbErqBuildUpFC: 11100,
        shortOverValueFC: 59.33,
        shortOverValueBDT: 7120.79,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 44407.4,
        adjustmentDate: iso(-52),
      },
    ],
  },
  {
    id: 'lc-21',
    lcNumber: 'ILC-2026-0212',
    beneficiary: 'VF Corporation Sourcing',
    issuingBank: 'Lloyds Bank plc',
    branch: 'City of London Branch',
    location: 'London, UK',
    advisingBank: 'Bank Asia Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 146000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-132),
    issueDate: iso(-134),
    acceptanceDate: iso(-129),
    maturityDate: iso(-71),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Tanvir Ahmed',
    media: 'SWIFT TT',
    remarks: 'Fully realized; source tax and ERQ build-up reconciled.',
    realizations: [
      {
        id: 'lc-21-r1',
        date: iso(-81),
        currency: 'USD',
        amountFC: 146000,
        exchangeRate: 119.31,
        fddPayOrderDate: iso(-79),
        scbErqBuildUpFC: 21900,
        shortOverValueFC: 64.46,
        shortOverValueBDT: 7690.72,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 104515.56,
        adjustmentDate: iso(-67),
      },
    ],
  },
  {
    id: 'lc-22',
    lcNumber: 'ILC-2026-0213',
    beneficiary: "Kohl's Department Stores",
    issuingBank: 'Skandinaviska Enskilda Banken',
    branch: 'Stockholm Branch',
    location: 'Stockholm, Sweden',
    advisingBank: 'Trust Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 72000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-94),
    issueDate: iso(-96),
    maturityDate: iso(-18),
    unit: 'Israq Spinning Mills LTD',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'No realization received past maturity; advising bank following up with issuing bank on payment status.',
    advBankReminderDate: iso(-1),
    nextVisitingDate: iso(3),
    realizations: [],
  },
  {
    id: 'lc-23',
    lcNumber: 'ILC-2026-0214',
    beneficiary: 'JCPenney Purchasing Corp.',
    issuingBank: 'NatWest Group',
    branch: 'Bishopsgate Branch',
    location: 'London, UK',
    advisingBank: 'Pubali Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 221000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-79),
    issueDate: iso(-81),
    maturityDate: iso(-17),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: 'Issuing bank cited documentation discrepancy; realization delayed past maturity.',
    advBankReminderDate: iso(-1),
    issuingBankVisitingDate: iso(-22),
    nextVisitingDate: iso(6),
    realizations: [],
  },
  {
    id: 'lc-24',
    lcNumber: 'ILC-2026-0215',
    beneficiary: "Macy's Merchandising Group",
    issuingBank: 'Erste Group Bank AG',
    branch: 'Vienna Branch',
    location: 'Vienna, Austria',
    advisingBank: 'Dhaka Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 162000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-95),
    issueDate: iso(-97),
    maturityDate: iso(-32),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Issuing bank cited documentation discrepancy; realization delayed past maturity.',
    advBankReminderDate: iso(-4),
    issuingBankVisitingDate: iso(-27),
    nextVisitingDate: iso(5),
    realizations: [],
  },
  {
    id: 'lc-25',
    lcNumber: 'ILC-2026-0216',
    beneficiary: 'Nordstrom Product Group',
    issuingBank: 'Credit Agricole CIB',
    branch: 'Paris La Defense Branch',
    location: 'Paris, France',
    advisingBank: 'NCC Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 201000,
    billType: 'LDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-98),
    issueDate: iso(-100),
    acceptanceDate: iso(-95),
    maturityDate: iso(-14),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Tanvir Ahmed',
    media: 'FDD',
    remarks: 'No realization received past maturity; advising bank following up with issuing bank on payment status.',
    advBankReminderDate: iso(-5),
    nextVisitingDate: iso(2),
    realizations: [
      {
        id: 'lc-25-r1',
        date: iso(-27),
        currency: 'USD',
        amountFC: 79048,
        exchangeRate: 120.09,
        fddPayOrderDate: iso(-25),
        scbErqBuildUpFC: 11857.2,
        shortOverValueFC: 25.61,
        shortOverValueBDT: 3075.5,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 94928.74,
      },
    ],
  },
  {
    id: 'lc-26',
    lcNumber: 'ILC-2026-0217',
    beneficiary: 'Under Armour Inc.',
    issuingBank: 'Standard Bank of South Africa',
    branch: 'Cape Town Branch',
    location: 'Cape Town, South Africa',
    advisingBank: 'NCC Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 211000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-83),
    issueDate: iso(-85),
    maturityDate: iso(-10),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: 'Issuing bank cited documentation discrepancy; realization delayed past maturity.',
    advBankReminderDate: iso(-5),
    nextVisitingDate: iso(11),
    realizations: [],
  },
  {
    id: 'lc-27',
    lcNumber: 'ILC-2026-0218',
    beneficiary: 'Puma SE',
    issuingBank: 'DBS Bank Ltd',
    branch: 'Marina Bay Branch',
    location: 'Singapore',
    advisingBank: 'Bank Asia Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 250000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-101),
    issueDate: iso(-103),
    acceptanceDate: iso(-98),
    maturityDate: iso(-36),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Issuing bank cited documentation discrepancy; realization delayed past maturity.',
    advBankReminderDate: iso(-3),
    nextVisitingDate: iso(3),
    realizations: [],
  },
  {
    id: 'lc-28',
    lcNumber: 'ILC-2026-0219',
    beneficiary: 'Adidas Sourcing Ltd',
    issuingBank: 'OCBC Bank',
    branch: 'Raffles Place Branch',
    location: 'Singapore',
    advisingBank: 'Midland Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 115000,
    billType: 'LDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-76),
    issueDate: iso(-78),
    maturityDate: iso(-15),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Partial realization only; balance overdue and under follow-up with issuing bank.',
    advBankReminderDate: iso(-7),
    issuingBankVisitingDate: iso(-34),
    nextVisitingDate: iso(6),
    realizations: [],
  },
  {
    id: 'lc-29',
    lcNumber: 'ILC-2026-0220',
    beneficiary: 'Nike Trading B.V.',
    issuingBank: 'NatWest Group',
    branch: 'Bishopsgate Branch',
    location: 'London, UK',
    advisingBank: 'Brac Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 243000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-96),
    issueDate: iso(-98),
    maturityDate: iso(-31),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Tanvir Ahmed',
    media: 'Pay Order',
    remarks: 'Partial realization only; balance overdue and under follow-up with issuing bank.',
    advBankReminderDate: iso(-6),
    nextVisitingDate: iso(8),
    realizations: [
      {
        id: 'lc-29-r1',
        date: iso(-42),
        currency: 'USD',
        amountFC: 118345,
        exchangeRate: 126.41,
        fddPayOrderDate: iso(-40),
        scbErqBuildUpFC: 17751.75,
        shortOverValueFC: -61.2,
        shortOverValueBDT: -7736.29,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 74799.96,
      },
    ],
  },
  {
    id: 'lc-30',
    lcNumber: 'ILC-2026-0221',
    beneficiary: 'New Look Retailers Ltd',
    issuingBank: 'Erste Group Bank AG',
    branch: 'Vienna Branch',
    location: 'Vienna, Austria',
    advisingBank: 'Bank Asia Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 178000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-102),
    issueDate: iso(-104),
    maturityDate: iso(-35),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Partial realization only; balance overdue and under follow-up with issuing bank.',
    advBankReminderDate: iso(-5),
    nextVisitingDate: iso(4),
    realizations: [],
  },
  {
    id: 'lc-31',
    lcNumber: 'ILC-2026-0222',
    beneficiary: 'River Island Clothing Co.',
    issuingBank: 'KEB Hana Bank',
    branch: 'Seoul Trade Branch',
    location: 'Seoul, South Korea',
    advisingBank: 'Dhaka Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 165000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-97),
    issueDate: iso(-99),
    maturityDate: iso(-29),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'No realization received past maturity; advising bank following up with issuing bank on payment status.',
    advBankReminderDate: iso(-6),
    issuingBankVisitingDate: iso(-12),
    nextVisitingDate: iso(14),
    realizations: [],
  },
  {
    id: 'lc-32',
    lcNumber: 'ILC-2026-0223',
    beneficiary: 'Debenhams Retail plc',
    issuingBank: 'Qatar National Bank',
    branch: 'Doha Branch',
    location: 'Doha, Qatar',
    advisingBank: 'One Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 128000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-75),
    issueDate: iso(-77),
    acceptanceDate: iso(-72),
    maturityDate: iso(5),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: 'On track; documents already negotiated, balance expected via advising bank before maturity.',
    advBankReminderDate: iso(-4),
    realizations: [],
  },
  {
    id: 'lc-33',
    lcNumber: 'ILC-2026-0224',
    beneficiary: 'ASDA Stores Ltd',
    issuingBank: 'Swedbank AB',
    branch: 'Stockholm Trade Branch',
    location: 'Stockholm, Sweden',
    advisingBank: 'Dhaka Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 240000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-77),
    issueDate: iso(-79),
    maturityDate: iso(0),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Awaiting final tranche; no discrepancy reported by issuing bank.',
    advBankReminderDate: iso(-2),
    realizations: [],
  },
  {
    id: 'lc-34',
    lcNumber: 'ILC-2026-0225',
    beneficiary: "Sainsbury's Argos",
    issuingBank: 'Swedbank AB',
    branch: 'Stockholm Trade Branch',
    location: 'Stockholm, Sweden',
    advisingBank: 'The City Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 114000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-68),
    issueDate: iso(-70),
    acceptanceDate: iso(-65),
    maturityDate: iso(4),
    unit: 'Israq Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Nusrat Jahan',
    media: 'FDD',
    remarks: 'On track; documents already negotiated, balance expected via advising bank before maturity.',
    advBankReminderDate: iso(-5),
    realizations: [
      {
        id: 'lc-34-r1',
        date: iso(-13),
        currency: 'USD',
        amountFC: 60867,
        exchangeRate: 118.22,
        fddPayOrderDate: iso(-11),
        scbErqBuildUpFC: 9130.05,
        shortOverValueFC: -76.41,
        shortOverValueBDT: -9033.19,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 71956.97,
      },
    ],
  },
  {
    id: 'lc-35',
    lcNumber: 'ILC-2026-0226',
    beneficiary: 'Monoprix S.A.',
    issuingBank: 'China Construction Bank',
    branch: 'Beijing Branch',
    location: 'Beijing, China',
    advisingBank: 'Eastern Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 175000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-67),
    issueDate: iso(-69),
    maturityDate: iso(7),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Kamrul Hasan',
    media: 'Pay Order',
    remarks: 'Maturity approaching; advising bank confirmed remittance instruction on file.',
    advBankReminderDate: iso(-3),
    realizations: [
      {
        id: 'lc-35-r1',
        date: iso(-17),
        currency: 'USD',
        amountFC: 80121,
        exchangeRate: 131,
        fddPayOrderDate: iso(-15),
        scbErqBuildUpFC: 12018.15,
        shortOverValueFC: 55.34,
        shortOverValueBDT: 7249.54,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 104958.51,
      },
    ],
  },
  {
    id: 'lc-36',
    lcNumber: 'ILC-2026-0227',
    beneficiary: 'Auchan Retail International',
    issuingBank: 'OCBC Bank',
    branch: 'Raffles Place Branch',
    location: 'Singapore',
    advisingBank: 'Pubali Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 91000,
    billType: 'LDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-80),
    issueDate: iso(-82),
    maturityDate: iso(7),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Sadia Islam',
    media: 'SWIFT TT',
    remarks: 'Maturity approaching; advising bank confirmed remittance instruction on file.',
    advBankReminderDate: iso(-2),
    realizations: [
      {
        id: 'lc-36-r1',
        date: iso(-12),
        currency: 'USD',
        amountFC: 48704,
        exchangeRate: 127.84,
        fddPayOrderDate: iso(-10),
        scbErqBuildUpFC: 7305.6,
        shortOverValueFC: -37.54,
        shortOverValueBDT: -4799.11,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 31131.6,
      },
    ],
  },
  {
    id: 'lc-37',
    lcNumber: 'ILC-2026-0228',
    beneficiary: 'El Corte Ingles S.A.',
    issuingBank: 'Emirates NBD Bank',
    branch: 'Dubai Trade Branch',
    location: 'Dubai, UAE',
    advisingBank: 'Pubali Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 230000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-83),
    issueDate: iso(-85),
    acceptanceDate: iso(-80),
    maturityDate: iso(2),
    unit: 'Israq Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'On track; documents already negotiated, balance expected via advising bank before maturity.',
    advBankReminderDate: iso(-3),
    realizations: [],
  },
  {
    id: 'lc-38',
    lcNumber: 'ILC-2026-0229',
    beneficiary: 'Mango MNG Holding',
    issuingBank: 'Standard Bank of South Africa',
    branch: 'Cape Town Branch',
    location: 'Cape Town, South Africa',
    advisingBank: 'Trust Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 201000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-60),
    issueDate: iso(-62),
    maturityDate: iso(4),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Nusrat Jahan',
    media: 'FDD',
    remarks: 'Awaiting final tranche; no discrepancy reported by issuing bank.',
    advBankReminderDate: iso(-4),
    realizations: [
      {
        id: 'lc-38-r1',
        date: iso(-16),
        currency: 'USD',
        amountFC: 99674,
        exchangeRate: 127.92,
        fddPayOrderDate: iso(-14),
        scbErqBuildUpFC: 14951.1,
        shortOverValueFC: -39.54,
        shortOverValueBDT: -5057.96,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 127502.98,
      },
    ],
  },
  {
    id: 'lc-39',
    lcNumber: 'ILC-2026-0230',
    beneficiary: 'Zeeman Textiles Supers',
    issuingBank: 'Lloyds Bank plc',
    branch: 'City of London Branch',
    location: 'London, UK',
    advisingBank: 'NCC Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 100000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-63),
    issueDate: iso(-65),
    maturityDate: iso(0),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Kamrul Hasan',
    media: 'Pay Order',
    remarks: "Final tranche pending buyer's quality acceptance sign-off.",
    advBankReminderDate: iso(-4),
    realizations: [
      {
        id: 'lc-39-r1',
        date: iso(-24),
        currency: 'USD',
        amountFC: 67710,
        exchangeRate: 128.7,
        fddPayOrderDate: iso(-22),
        scbErqBuildUpFC: 10156.5,
        shortOverValueFC: -63.75,
        shortOverValueBDT: -8204.62,
        sourceTaxRate: 0.005,
        sourceTaxBDT: 43571.39,
      },
    ],
  },
  {
    id: 'lc-40',
    lcNumber: 'ILC-2026-0231',
    beneficiary: 'Bestseller A/S',
    issuingBank: 'UniCredit Bank AG',
    branch: 'Munich Trade Branch',
    location: 'Munich, Germany',
    advisingBank: 'Mercantile Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 185000,
    billType: 'IDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-51),
    issueDate: iso(-53),
    maturityDate: iso(30),
    unit: 'Israq Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Usance LC running normally; no issues reported to date.',
    realizations: [],
  },
  {
    id: 'lc-41',
    lcNumber: 'ILC-2026-0232',
    beneficiary: 'COS (H&M Group)',
    issuingBank: 'TD Bank Group',
    branch: 'Toronto Financial District',
    location: 'Toronto, Canada',
    advisingBank: 'Eastern Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 211000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-31),
    issueDate: iso(-33),
    acceptanceDate: iso(-28),
    maturityDate: iso(42),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: "Balance expected in further tranches per buyer's payment schedule.",
    realizations: [],
  },
  {
    id: 'lc-42',
    lcNumber: 'ILC-2026-0233',
    beneficiary: 'Esprit Holdings Ltd',
    issuingBank: 'Bank of America N.A.',
    branch: 'Charlotte Trade Branch',
    location: 'Charlotte, USA',
    advisingBank: 'Mutual Trust Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 135000,
    billType: 'LDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(-45),
    issueDate: iso(-47),
    maturityDate: iso(17),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Documents lodged; realization expected on/around maturity.',
    realizations: [],
  },
  {
    id: 'lc-43',
    lcNumber: 'ILC-2026-0234',
    beneficiary: 'Benetton Group S.r.l.',
    issuingBank: 'Credit Agricole CIB',
    branch: 'Paris La Defense Branch',
    location: 'Paris, France',
    advisingBank: 'Dutch-Bangla Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 129000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-24),
    issueDate: iso(-26),
    maturityDate: iso(62),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Usance LC running normally; no issues reported to date.',
    realizations: [],
  },
  {
    id: 'lc-44',
    lcNumber: 'ILC-2026-0235',
    beneficiary: 'OVS S.p.A.',
    issuingBank: 'ANZ Banking Group',
    branch: 'Melbourne Corporate Branch',
    location: 'Melbourne, Australia',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 121000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(2),
    issueDate: iso(0),
    maturityDate: iso(76),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Kamrul Hasan',
    media: 'SWIFT TT',
    remarks: 'Usance LC running normally; no issues reported to date.',
    realizations: [
      {
        id: 'lc-44-r1',
        date: iso(31),
        currency: 'USD',
        amountFC: 42003,
        exchangeRate: 129.59,
        fddPayOrderDate: iso(33),
        scbErqBuildUpFC: 6300.45,
        shortOverValueFC: -54.11,
        shortOverValueBDT: -7012.11,
        sourceTaxRate: 0.006,
        sourceTaxBDT: 32659.01,
      },
    ],
  },
  {
    id: 'lc-45',
    lcNumber: 'ILC-2026-0236',
    beneficiary: 'Takko Fashion GmbH',
    issuingBank: 'Royal Bank of Canada',
    branch: 'Toronto Trade Branch',
    location: 'Toronto, Canada',
    advisingBank: 'One Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 102000,
    billType: 'LDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(5),
    issueDate: iso(3),
    maturityDate: iso(91),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Awaiting second tranche; buyer confirmed remittance instruction on file.',
    realizations: [],
  },
  {
    id: 'lc-46',
    lcNumber: 'ILC-2026-0237',
    beneficiary: 'KiK Textilien und Non-Food',
    issuingBank: 'First Abu Dhabi Bank',
    branch: 'Abu Dhabi Branch',
    location: 'Abu Dhabi, UAE',
    advisingBank: 'Prime Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 146000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-20),
    issueDate: iso(-22),
    maturityDate: iso(59),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: "Balance expected in further tranches per buyer's payment schedule.",
    realizations: [],
  },
  {
    id: 'lc-47',
    lcNumber: 'ILC-2026-0238',
    beneficiary: 'Tchibo GmbH',
    issuingBank: 'Absa Group Ltd',
    branch: 'Johannesburg Branch',
    location: 'Johannesburg, South Africa',
    advisingBank: 'Eastern Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 128000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(10),
    issueDate: iso(8),
    acceptanceDate: iso(13),
    maturityDate: iso(70),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: 'Usance LC running normally; no issues reported to date.',
    realizations: [],
  },
  {
    id: 'lc-48',
    lcNumber: 'ILC-2026-0239',
    beneficiary: 'Otto Group Sourcing',
    issuingBank: 'Commonwealth Bank of Australia',
    branch: 'Sydney Trade Branch',
    location: 'Sydney, Australia',
    advisingBank: 'Brac Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 213000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-27),
    issueDate: iso(-29),
    acceptanceDate: iso(-24),
    maturityDate: iso(32),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    realizationPerson: 'Kamrul Hasan',
    media: 'Pay Order',
    remarks: "Balance expected in further tranches per buyer's payment schedule.",
    realizations: [
      {
        id: 'lc-48-r1',
        date: iso(-10),
        currency: 'USD',
        amountFC: 90766,
        exchangeRate: 130.21,
        fddPayOrderDate: iso(-8),
        scbErqBuildUpFC: 13614.9,
        shortOverValueFC: -18.47,
        shortOverValueBDT: -2404.98,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 118186.41,
      },
    ],
  },
  {
    id: 'lc-49',
    lcNumber: 'ILC-2026-0240',
    beneficiary: 'Hugo Boss AG',
    issuingBank: 'ING Bank N.V.',
    branch: 'Amsterdam Head Office',
    location: 'Amsterdam, Netherlands',
    advisingBank: 'Dutch-Bangla Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 89000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-33),
    issueDate: iso(-35),
    maturityDate: iso(32),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Usance LC running normally; no issues reported to date.',
    realizations: [],
  },
  {
    id: 'lc-50',
    lcNumber: 'ILC-2026-0241',
    beneficiary: 's.Oliver Group Sourcing',
    issuingBank: 'Qatar National Bank',
    branch: 'Doha Branch',
    location: 'Doha, Qatar',
    advisingBank: 'NCC Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 102000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(6),
    issueDate: iso(4),
    acceptanceDate: iso(9),
    maturityDate: iso(76),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    realizationPerson: 'Tanvir Ahmed',
    media: 'Pay Order',
    remarks: 'Awaiting second tranche; buyer confirmed remittance instruction on file.',
    realizations: [
      {
        id: 'lc-50-r1',
        date: iso(44),
        currency: 'USD',
        amountFC: 52434,
        exchangeRate: 126.15,
        fddPayOrderDate: iso(46),
        scbErqBuildUpFC: 7865.1,
        shortOverValueFC: 51.26,
        shortOverValueBDT: 6466.45,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 66145.49,
      },
    ],
  },
  {
    id: 'lc-51',
    lcNumber: 'ILC-2026-0242',
    beneficiary: 'Matalan Retail Ltd',
    issuingBank: 'Barclays Bank plc',
    branch: 'Canary Wharf Branch',
    location: 'London, UK',
    advisingBank: 'Uttara Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 203000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(5),
    issueDate: iso(3),
    maturityDate: iso(81),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Recently opened; no realization activity yet.',
    realizations: [],
  },
  {
    id: 'lc-52',
    lcNumber: 'ILC-2026-0243',
    beneficiary: 'Peacocks Stores Ltd',
    issuingBank: 'NatWest Group',
    branch: 'Bishopsgate Branch',
    location: 'London, UK',
    advisingBank: 'The City Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 194000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-11),
    issueDate: iso(-13),
    maturityDate: iso(51),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: 'Documents lodged; realization expected on/around maturity.',
    realizations: [],
  },
  {
    id: 'lc-53',
    lcNumber: 'ILC-2026-0244',
    beneficiary: 'George at ASDA',
    issuingBank: 'TD Bank Group',
    branch: 'Toronto Financial District',
    location: 'Toronto, Canada',
    advisingBank: 'Dhaka Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 155000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-18),
    issueDate: iso(-20),
    maturityDate: iso(53),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: 'Usance LC running normally; no issues reported to date.',
    realizations: [],
  },
  {
    id: 'lc-54',
    lcNumber: 'ILC-2026-0245',
    beneficiary: 'Woolworths Holdings Ltd',
    issuingBank: 'Bank of Montreal',
    branch: 'Montreal Branch',
    location: 'Montreal, Canada',
    advisingBank: 'Pubali Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 120000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-69),
    issueDate: iso(-71),
    maturityDate: iso(19),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: 'Awaiting second tranche; buyer confirmed remittance instruction on file.',
    realizations: [],
  },
  {
    id: 'lc-55',
    lcNumber: 'ILC-2026-0246',
    beneficiary: 'Shoprite Sourcing Pty Ltd',
    issuingBank: 'KEB Hana Bank',
    branch: 'Seoul Trade Branch',
    location: 'Seoul, South Korea',
    advisingBank: 'Trust Bank Ltd, Dhaka',
    currency: 'USD',
    lcValue: 157000,
    billType: 'LDBC',
    discountStatus: 'Not Discounted',
    entryDate: iso(27),
    issueDate: iso(25),
    acceptanceDate: iso(30),
    maturityDate: iso(89),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    remarks: "Balance expected in further tranches per buyer's payment schedule.",
    realizations: [],
  },
  {
    id: 'lc-56',
    lcNumber: 'ILC-2026-0247',
    beneficiary: 'Canadian Tire Sourcing Inc.',
    issuingBank: 'Barclays Bank plc',
    branch: 'Canary Wharf Branch',
    location: 'London, UK',
    advisingBank: 'Uttara Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 85000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-23),
    issueDate: iso(-25),
    acceptanceDate: iso(-20),
    maturityDate: iso(40),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: 'Recently opened; no realization activity yet.',
    realizations: [],
  },
  {
    id: 'lc-57',
    lcNumber: 'ILC-2026-0248',
    beneficiary: "Hudson's Bay Company",
    issuingBank: 'JPMorgan Chase Bank N.A.',
    branch: 'New York Head Office',
    location: 'New York, USA',
    advisingBank: 'Brac Bank Ltd, Gulshan Branch',
    currency: 'USD',
    lcValue: 165000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-12),
    issueDate: iso(-14),
    maturityDate: iso(73),
    unit: 'Green Dyeing & Finishing',
    responsiblePerson: 'Shafiul Islam',
    remarks: "Balance expected in further tranches per buyer's payment schedule.",
    realizations: [],
  },
  {
    id: 'lc-58',
    lcNumber: 'ILC-2026-0249',
    beneficiary: 'Loblaw Companies Ltd',
    issuingBank: 'Nordea Bank Abp',
    branch: 'Helsinki Corporate Branch',
    location: 'Helsinki, Finland',
    advisingBank: 'NCC Bank Ltd, Motijheel Branch',
    currency: 'USD',
    lcValue: 62000,
    billType: 'IDBC',
    discountStatus: 'Discounted',
    entryDate: iso(-21),
    issueDate: iso(-23),
    maturityDate: iso(38),
    unit: 'Apex Spinning Mills',
    responsiblePerson: 'Md. Anisur Rahman',
    realizationPerson: 'Kamrul Hasan',
    media: 'SWIFT TT',
    remarks: 'Awaiting second tranche; buyer confirmed remittance instruction on file.',
    realizations: [
      {
        id: 'lc-58-r1',
        date: iso(-9),
        currency: 'USD',
        amountFC: 24561,
        exchangeRate: 120.32,
        fddPayOrderDate: iso(-7),
        scbErqBuildUpFC: 3684.15,
        shortOverValueFC: 66.68,
        shortOverValueBDT: 8022.94,
        sourceTaxRate: 0.01,
        sourceTaxBDT: 29551.8,
      },
    ],
  },
  {
    id: 'lc-59',
    lcNumber: 'ILC-2026-0250',
    beneficiary: 'Ross Stores Inc.',
    issuingBank: 'Nordea Bank Abp',
    branch: 'Helsinki Corporate Branch',
    location: 'Helsinki, Finland',
    advisingBank: 'Standard Chartered Bank, Dhaka Main Branch',
    currency: 'USD',
    lcValue: 243000,
    billType: 'LDBC',
    discountStatus: 'Discounted',
    entryDate: iso(16),
    issueDate: iso(14),
    maturityDate: iso(99),
    unit: 'Desh Fabrics & Weaving',
    responsiblePerson: 'Farhana Akter',
    remarks: 'Awaiting second tranche; buyer confirmed remittance instruction on file.',
    realizations: [],
  },
];
